describe('Log In', () => {
    it('should see login page', () => {
        cy.visit('/').title().should('eq', 'Login | Fantasy Eats')
    })
    it('can see email validation error', () => {
        cy.visit('/')
            .get('[placeholder="Email"]')
            .type('some_email_6@gmail')
            .get('.text-red-500')
            .should('have.text', 'Please enter a valid email')
            .get('[placeholder="Email"]')
            .clear()
            .get('.text-red-500')
            .should('have.text', 'Email is required')
    })
    it('can see password validation error', () => {
        cy.visit('/')
            .get('[placeholder="Email"]')
            .type('some_email_6@gmail.com')
            .get('[placeholder="Password"]')
            .type('12345')
            .clear()
            .get('.text-red-500')
            .should('have.text', 'Password is required')
    })
    it('login', () => {
        // cy.visit('/')
        //     .get('[placeholder="Email"]')
        //     .type('customer_email_1@gmail.com')
        //     .get('[placeholder="Password"]')
        //     .type('12345')
        //     .get('.text-lg')
        //     .should('not.have.class', 'pointer-events-none')
        //     .click()
        //     .window()
        //     .its('localStorage.fantasy-token')
        //     .should('be.a', 'string')
        //@ts-ignore
        cy.login('customer_email_1@gmail.com', '12345')
    })
    it.skip('sign up', () => {
        cy.visit('/create-account')
    })
})
